### ISSUE TITLE
Separation of WDS website and WDS components into different GH repos

### ISSUE THREAD

**Issue by juliaelman** [18F/web-design-standards#1343]
# Description

The core team has decided to move forward with the separation of the website/docs codebase and the components code into different repos. Based off of [user research and feedback](https://github.com/18F/web-design-standards-ux/tree/master/June_Chicago_User_Observation), our goal is to create a better understanding of how the two work together both for the users of the Standards and our contributor base.

## Tasks
- [x] [Comms strategy for announcing split to user base](https://github.com/18F/web-design-standards/issues/1393) 
- [x] Create new repo with website code separated out
- [x] Create `je-split_repo` branch (FKA `split-repo`)
- [x] [Remove website dependencies from `web-design-standards`](https://github.com/18F/web-design-standards/issues/1394)
- [x] [Remove website code from `web-design-standards`](https://github.com/18F/web-design-standards/issues/1395)
- [x] [Test Standards as stand alone package](https://github.com/18F/web-design-standards/issues/1396)
- [x] [Update documentation](https://github.com/18F/web-design-standards/issues/1397)
- [x] [Documentation review](https://github.com/18F/web-design-standards/issues/1398)
- [x] [QA code base](https://github.com/18F/web-design-standards/issues/1399)

## Additional information

We'll need to be clear in our comms and outreach to our users prior to the finalization of this work. See https://github.com/18F/web-design-standards/issues/1341 for the long term comms plan for scheduling this messaging.

**Comment by kategarklavs** [comment]
@juliaelman Hey! Thanks for tagging me in this. I'll block off some time on your calendar (and/or on other folks' calendars) to pick your brains about the necessary documentation.

**Comment by joshbruce** [comment]
Tagging my team so they are aware: @BrianGilmanGSA, @ChristyHermansen, @jenbesergsa

**Comment by juliaelman** [comment]
The groundwork has been completed for the new docs/website repo here: https://github.com/18F/web-design-standards-docs

I have added a disclaimer in the [README.md](https://github.com/18F/web-design-standards-docs/blob/master/README.md) stating referencing back to this issue.

**Comment by yozlet** [comment]
The new [web-design-standards-docs repo](https://github.com/18F/web-design-standards-docs) is now auto-deploying to https://wds-docs.apps.cloud.gov/ (`master` branch) and https://wds-docs-staging.apps.cloud.gov/ (`staging` branch). Right now we're all just working straight into `master` but before launch we'll resume the PR -> staging -> master workflow.

**Comment by shawnbot** [comment]
FYI, I'm checking off the website dependency and code items on this list, but #1394 and #1395 remain open for now.

**Comment by juliaelman** [comment]
Technical documentation updated here: https://github.com/18F/web-design-standards/pull/1420
