### ISSUE TITLE
[Content] Develop metrics-tracking plan 

### ISSUE THREAD

**Issue by kategarklavs** [18F/web-design-standards#1401]
## Description

This was initially part of #1341 — creating a new issue so I can keep track of this task once I close #1341.

Part of our longer-term comms plan is tracking the success of our strategies. Some to-dos:

- [x] Create initial definitions of success for various content channels/types
- [x] Draft metrics-tracking plan
- [ ] (Ongoing) Periodically evaluate our plan and modify, as needed
- [ ] (Ongoing) Report out to the team

**Comment by kategarklavs** [comment]
Being that the repo-split comms plan is in solid shape, I'll claim this task!

**Comment by kategarklavs** [comment]
I've got a draft document going here: https://docs.google.com/a/gsa.gov/document/d/1KcEzMmop_kbp_eWf-af9OJja_zCvraSprv7xKw78vYU/edit?usp=sharing

**Comment by kategarklavs** [comment]
@jameshupp and I have created a draft of the plan (which will undoubtedly change a bit as time goes on). Up next: filing individual issues for sub-steps of the plan.

**Comment by kategarklavs** [comment]
(On that ^^ note, going to close this issue, for now, as we have an initial plan. @jameshupp — if you'd like to reopen, please do!)
