### ISSUE TITLE
[Website] Plan for HTML templates 

### ISSUE THREAD

**Issue by donjo** [18F/web-design-standards#1402]
## Description

This issue covers the second phase of the HTML template work for the WDS standards. Through some sketching sessions and prototyping we'll decide how users access ready-to-go HTML templates that consume the standards.

This issue doesn't cover the work that goes into creating each individual template or writing any of the content and code required to showcase the templates on the WDS site. 

## Todo list

- [x] Host a sketching session to clarify the problem with the WDS team
- [ ] Decide where access to HTML templates should live on the WDS site
- [ ] Decide how the HTML templates should be described to users
- [ ] Decide how many and what kind of HTML templates should be offered

## Additional information [optional]

See #1379 for discussion around possibilities and inspiration

**Comment by bradnunnally** [comment]
Here are next steps from the teams meeting @donjo and @lauraponce we had yesterday:

- MVP & Fidelity

- [ ] Create a landing page that describes the purpose and use of templates
- [ ] Create a template for a document based site
- [ ] Create a template for a marketing site
- [ ] Fidelity of of the templates should use the colors and styling of the WDS to give people the best starting. 

- Location
- [ ] Include as a main nav item with linking from Getting Started

**Comment by jameshupp** [comment]
Are the templates going to be rendered from HTML, or are they images? And if they're images, are they only going to be a single rendered  Thinking about things like whether we need sample copy in pull-down menus.

**Comment by donjo** [comment]
@jameshupp They will be rendered from HTML in a demo page, similar to how the headers documentation works currently.

**Comment by jameshupp** [comment]
Working on copy in this doc. Noted here for team visibility. https://docs.google.com/document/d/11jrn9KAVwbGv2EQ3MmZRn2F9Ia_u85PQAYP-59QdJZE/edit#

**Comment by kategarklavs** [comment]
Added documentation page copy and asked @jameshupp and @maya to review it (I'm happy to add more sections/expand on the existing ones, if necessary).
