### ISSUE TITLE
[Documentation] Create release-notes checklist

### ISSUE THREAD

**Issue by kategarklavs** [18F/web-design-standards#1466]
## Description

This is a subtask of #1401. To make our release notes easier to read/more valuable to our users, we'd like to draft guidelines for the creation of said notes, along with a pre-publication checklist.

To-dos:

- [x] Draft high-level guidelines (incl. notes template)
- [x] Create a checklist of everything release notes need to have before they're published
- [x] Get feedback from team
- [x] Publish

Not 100% sure yet what publication entails — perhaps inclusion in our wiki?

**Comment by kategarklavs** [comment]
Assigning myself this issue, as @jameshupp is working on creating an easy-to-use/easy-to-locate metrics tracking sheet 😎

**Comment by kategarklavs** [comment]
Okey doke: Initial draft of the guidelines/checklist doc is here: 

https://docs.google.com/a/gsa.gov/document/d/1ogpJvc_8qor9_Hv9B-CKvB0Qeqn5ImbdgF3tYNmD870/edit?usp=sharing

Note: It's still pretty messy and could definitely benefit from team feedback!

You'll also notice I created and linked to a project-specific style sheet. Haven't gotten started on this yet, but I'll create an issue for it and get to work. An initial draft shouldn't take more than a day or two. 

cc @juliaelman @jameshupp & co.

**Comment by juliaelman** [comment]
@kategarklavs looks great and left some notes! 🎉

**Comment by kategarklavs** [comment]
@juliaelman Excellent! Going to check those out shortly 😎

**Comment by kategarklavs** [comment]
Good news! I've updated the guidelines, done a final edit, and published them to the wiki (they live in a new category — Documentation). Going to close this issue out 🎉
