### ISSUE TITLE
[Documentation]: WDS-specific style guide 

### ISSUE THREAD

**Issue by kategarklavs** [18F/web-design-standards#1474]
## Description

Creating a project-specific style guide will help us ensure that our documentation is easy (and possibly fun) to read. This guide will cover preferred capitalizations for often-used words, voice and tone guidance, and anything else that seems useful to content folks involved with the Standards.

As the guide is a living document, there's also a "last updated" line at the top to give folks a sense of how current the current version is. 

Draft is here:

https://docs.google.com/a/gsa.gov/document/d/1wdJm3SK-gXTXEyls4p6Ot582OSQP-IxLbhqZruMDz-U/edit?usp=sharing

## To-dos

- [x] Create a first draft of the guide 
- [x] Review and copy edit said draft 
- [x] Share the draft with the team and encourage everyone to update the guide as they see fit! (Also remind folks to change the "last updated" date when they do make updates.)

**Comment by kategarklavs** [comment]
Okey doke — this issue is done! We now have an mvp style sheet, which will live in the wiki. All team members are welcome to contribute 👍
