### ISSUE TITLE
18F WDS Header and Footer issue log

### ISSUE THREAD

**Issue by davidstenger** [18F/web-design-standards#1508]
Attached is the Google link containing all the Testing results for the [18F WDS header and footer](https://drive.google.com/drive/folders/0ByVEB-PJZ25qcm9DazdmQWhsRDQ?usp=sharing). The folder contains:

- An Issue Log with the testing results [S508_WebChecklist_WDS-header_footer](https://docs.google.com/a/gsa.gov/spreadsheets/d/1IM7xFsmPciEEQh5sd7gvxWMWd_Xw3fYTZ4iKkISXixk/edit?usp=sharing).
- A folder containing screen captures illustrating the issues failed during testing.
Once you’ve had a chance to the review the testing results please contact me if you have any questions.
 
Here is the link that shows how error handling should be handled for all form fields, [Form Validation](https://assets.cms.gov/resources/framework/3.4.1/Pages/#formvalidator).

**Comment by jpyuda** [comment]
@davidstenger I encourage you to post the issues as individual github issues so that we can better track progress, keep discussion clear (as opposed to discussing several possible issues in one thread) and so that non-GSA staff who use and contribute to the work can follow along.

Thanks!

**Comment by shawnbot** [comment]
Thanks, @davidstenger! The feedback your team gave us is very welcome and helpful. We're going to start adding individual issues from the doc that you shared, and if you'd like we can tag you on them as we go. We'll close this issue once they're all in.

**Comment by shawnbot** [comment]
I've also created a ["[Partner] USA.gov" label](https://github.com/18F/web-design-standards/issues?q=is%3Aissue+is%3Aopen+label%3A%22%5BPartner%5D+USA.gov%22) that we can use to tag and filter issues for USA.gov.

**Comment by shawnbot** [comment]
Just to clarify: I'm working off both and the spreadsheet linked above and [this document](https://docs.google.com/document/d/1GAw0epAwQKKjq-sxG5MXdn50yWOA4i160hLn-jUBXRA/edit), which lists some specific changes that USA.gov makes (and some of which address accessibility issues listed in the spreadsheet).

**Comment by shawnbot** [comment]
Update: @davidstenger and his team are adding issues, and you can find them all under the [USA.gov label](https://github.com/18F/web-design-standards/issues?q=is%3Aissue+is%3Aopen+label%3A%22%5BPartner%5D+USA.gov%22). Here is a checklist for us to compare:

## Header and footer accessibility issues
- [x] Visual Appearance of Control Does Not Match Function #1644 
- [x] Expand/Collapse Images coded as CSS background images. #1645 
- [x] Users Not Notified that JavaScript is Required #1646 
- [x] Missing visual label for the Search field #1647 
- [x] Unnecessary aria-label used for the link #1648 
- [x] User is not informed about the Menu has been collapsed #1649 
- [x] Colors used in navigation bar it indicate currently selected status #1650 
- [x] Illogical Tab Order #1651 
- [x] Visual Focus Indicator Lost #1652 
- [x] Focus indicator is lost in Responsive view. #1653 
- [x] Missing ARIA Landmark role="search" #1654 
- [x] Focus indicator is not clearly visible on the Menu button. #1655 
- [x] Incorrect role is used for the Close button #1656 
- [x] Footer when reviewed on Mobile. #1657 
- [x] Missing Alt on Logo #1658 
- [x] Topic part of list items #1659 
- [ ] H6 ("I'm sure this is just because of the WDS page but we should never get to a H6 heading on a page.")
- [ ] Default browser focus

## Open questions re: header/footer implementation
- [x] JS error in uswds.js ("Uncaught TypeError: Cannot read property 'classList' of undefined") **fixed in #1606**
- [ ] Nav dropdown lists structure isn’t ideal for accessibility -- 3 separate lists instead of a single list
- [ ] HP Header: Scrolling menu issue, In iPhone (6), when you open the Menu and try to scroll down, the content in the background also moves. It should not.
- [ ] HP Header - Text Does Not Resize, with browser menu text resizing options. It is required to use “scalable fonts” or fonts that will allow the customer to increase and decrease text size using the browser functionality (e.g., `View > Text Size > Larger`). Use relative rather than absolute text sizes so that users can make text larger or smaller using the browser text resizing options.
- [ ] HP Content - Incorrect Heading Structure, Currently `H1` set for entire page and there is no `<h1>` on the page. Each page should have a level one heading (`<h1>`) defined at the start of the main content area to provide an easy way to identify the page. As a best practice, the text for the `<h1>` should include/match the text from the page `<title>`. Update the page to have an `<h1>`. This can be visible or can be hidden using CSS if you do not want to change the visual design of the page. Generally, visible `<h1>` headings are preferred to provide an easy means for all users to identify the page they are currently on. Code "Most Popular" as the H1 heading text.
- [ ] HP Header - Unnecessary list attributes are used, Each of the submenu items should be coded in one nested list to accurately convey the parent/child hierarchy of the item. All logically related items must be coded in one unordered list structure. List items_ExtendedHeader.png. Currently, these links are coded in in 3 or 4 unordered lists and the child elements are not being properly nested beneath the parent elements. this is confusing screen reader users.
