### ISSUE TITLE
Provide guidance on how to customize the system (colors, typography, etc.)

### ISSUE THREAD

**Issue by shawnbot** [18F/web-design-standards#1534]
The only place in the documentation that we even reference customization is a bullet item under [CSS Architecture](https://standards.usa.gov/getting-started/developers/#css-architecture) heading on the Getting Started page:

> **Global variables** are defined in the `_defaults.scss` file. Custom theming can be done by copying the `_variables.scss` file into your own project’s Sass folder, changing applicable variable values, and importing it before uswds in Sass.

There are a some big improvements that we could make here:
- [x] Update the above bullet item and the one below it that refer to `_defaults.scss` to only reference `core/variables`, because the former was deprecated in [v0.13.2](https://github.com/18F/web-design-standards/releases/tag/v0.13.2). See #1535 for the gory details.
- [ ] Expand "theming" to a separate section on customization
- [x] Document our SCSS variables, and note which ones are most relevant for theming/customization, namely:
  - [x] Colors: #960, #968
  - [x] Grid: #1236
- [x] Link directly to the relevant [source files](https://github.com/18F/web-design-standards/tree/master/src/stylesheets/core), and produce some standalone examples for customizing (maybe in gists to start?)
- [x] Refactor duplication of variables in [_defaults.scss](https://github.com/18F/web-design-standards/blob/master/src/stylesheets/core/_defaults.scss) and [_variables.scss](https://github.com/18F/web-design-standards/blob/master/src/stylesheets/core/_variables.scss), per #1532
- [x] Suggest a more future-friendly method of overriding variables, namely overriding individual variables instead of copying `_variables.scss` wholesale (which effectively locks those users in to _all_ of the default values) #1535
  - [x] Do some targeted outreach to current users and suggest ways to refactor their customizations to be more future-friendly
  - [x] Thoroughly document upgrade instructions for the next version

**Comment by juliaelman** [comment]
Ping @shawnbot to re-evaluate what is still needed on this issue and make any necessary updates.

**Comment by shawnbot** [comment]
Okay, I've updated the issue description and checked off a couple of the boxes. I think this is mostly a documentation issue, so maybe we should open something over in the other repo. @msecret, ping me if you have questions or thoughts!

**Comment by msecret** [comment]
I've completed the more simple part of this here: https://github.com/18F/web-design-standards-docs/pull/80. Will work on the more complex moving customization out as a separate PR.

**Comment by msecret** [comment]
I've put a draft of a more complete customization section here: https://github.com/18F/web-design-standards-docs/pull/81. It might make more sense to just merge this one and ignore `80`. It could be helpful to merge 80 if 81 takes a long time.

**Comment by shawnbot** [comment]
This is basically done, with the exception of a separate section on "theming". I'm going to close this and open a separate issue for that one, where we can discuss what that looks like in more detail. Thanks, @msecret!

**Comment by shawnbot** [comment]
Err sorry, there _is_ a [section on customization and theming](https://standards.usa.gov/getting-started/developers/#customizationtheming) already! Checking off that box, too.
