### ISSUE TITLE
Find IA placement and design for Web performance section of Standards site 

### ISSUE THREAD

**Issue by yowill** [18F/web-design-standards#1790]
## Description
Figure out where to place the research and artifacts of the Web Performance project on the Standards.usa.gov site, so that we can share this information and guidance out to agencies. Perhaps under the design principles section?

## Tasks
- [ ] Find a place in the ia to place it
- [ ] Design the pages
- [ ] Review with the team

**Comment by msecret** [comment]
There's also Getting Started -> For developers which goes over a lot of dev centered discussion such as architecture. But I don't think it really belongs in a "Getting started" section.

**Comment by bradnunnally** [comment]
Flagging this to be discussed at the stand up today. Is the content for this ready yet? While we can determine where it should live in the current site, doing any design work on the page without the content in at least a draft stage will not be possible.

**Comment by bradnunnally** [comment]
Meet with the Web Performance team yesterday and along with @shawnbot we determine that going through the effort of creating design comps for this is not necessary as we already have established page templates for the content that's being produced. 

The big lift here is to determine where it lives on the site for now. Two options were discussed:

1 Make it part of UI Components as an introductory to the whole section. 
2 Make it part of Getting Started, to help guide people from the beginning that Web Performance should be a focus for them. 

The second option is stronger, has it is presented to users from the beginning of their "journey" with the Standards. 

@yowill @shawnbot

**Comment by yowill** [comment]
I think #2 sounds like the better of the two options. We should integrate it into our Design principles by name too and maybe link over when we launch.

**Comment by bradnunnally** [comment]
@yowill I think that's a great idea. Lets create another issue for making that update to design principles. 

The rest of this can be closed out, and picked up when the development tasks is pulled in from our backlog and I can collaborate with @shawnbot to get it slotted in the right spot.

**Comment by shawnbot** [comment]
I really like the idea of performance being an explicit design principle.
