### ISSUE TITLE
Use Fractal

### ISSUE THREAD

**Issue by shawnbot** [18F/web-design-standards#1826]
We've decided to use [Fractal](http://fractal.build) to document our components and patterns. Here is something of a road map to consider, with Phase 1 being what we need to do now.

#### Phase 1
- [x] Get the basic scaffolding set up and building on Federalist
- [x] Migrate all [components](https://standards.usa.gov/components/) to the new system, with previews using the monolithic CSS and JS
- [x] Migrate test page templates (such as the header test page in #1823) to "kitchen sink" demo page

**Comment by shawnbot** [comment]
Phase 1: complete in #1827!
