### ISSUE TITLE
header design update

### ISSUE THREAD

**Issue by donjo** [18F/web-design-standards#2086]
spacing updates

**Comment by rtwell** [comment]
## Basic header
- [ ] Overall spacing adjustments
- [ ] Hover state should turn all elements blue
- [ ] Underline element should span the width of the words + the down carat, regardless of state
![image](https://user-images.githubusercontent.com/12564977/29524237-e77c785a-8654-11e7-8a2d-afe7d53e29d6.png)

### Basic header with mega menu
- [ ] Overall spacing adjustments
- [ ] Links should obey our grid 
- [ ] Provide examples of links that are longer and flow onto more than one line
- [ ] Background color for menu should be `#122E51`
![image](https://user-images.githubusercontent.com/12564977/29524958-d7ad0dd4-8656-11e7-8d53-00a0086cde57.png)

**Comment by rtwell** [comment]
## Extended header

- [ ]  Overall spacing adjustments
- [ ]  Hover state should turn all elements blue
- [ ]  Underline element should span the width of the words + the down carat, regardless of state
- [ ] Search icon should be `primary blue #0071bc`
- [ ] Utility links in the top right should underline on hover

![image](https://user-images.githubusercontent.com/12564977/29525111-46780a16-8657-11e7-8b77-04533547f848.png)

### Extended header with mega menu
- [ ]  Overall spacing adjustments
- [ ]  Links should obey our grid
- [ ]  Provide examples of links that are longer and flow onto more than one line
- [ ]  Background color for menu should be #122E51

![image](https://user-images.githubusercontent.com/12564977/29525591-c8f5d2ce-8658-11e7-8710-dedca4c2265a.png)

**Comment by rtwell** [comment]
## Mobile headers
### Basic header
#### Default state
- [ ] Spacing adjustments
![image](https://user-images.githubusercontent.com/12564977/29525727-3a1ae9a8-8659-11e7-81b9-fe5fa16886e1.png)

#### Menu open, nav collapsed
- [ ] Spacing adjustments
- [ ] Close "X" turns blue, and gets a little larger (`15px x 15px`)
- [ ] Larger "+" expandable icon
- [ ] Provide examples of links that are longer and flow onto more than one line
![image](https://user-images.githubusercontent.com/12564977/29526298-e9dae9b4-865a-11e7-9e46-0985eab5de85.png)


#### Menu open, nave expanded
- [ ] Spacing adjustments
- [ ] Provide examples of links that are longer and flow onto more than one line
![image](https://user-images.githubusercontent.com/12564977/29526127-67fd46e4-865a-11e7-8643-117bef40fa8f.png)
