### ISSUE TITLE
Update RELEASE.md

### ISSUE THREAD

**Issue by toolness** [18F/web-design-standards#2124]
I just followed the instructions under "when publishing a new release" in `RELEASE.md` to release [v1.3.1](https://github.com/18F/web-design-standards/releases/tag/v1.3.1) and wanted to note a few things:

- [x] Part (ii) is confusing. It says "for major and minor versions, publish a pre-release"; then it says "otherwise, run `npm version minor --no-tag` or `npm version major --no-tag`", which seems contradictory. Perhaps the second part should say "otherwise, run `npm version patch --no-tag`"? (#1906 might shed some light on this.)

- [x] In (iv), we mention that developers can tag the release using `git` from the command-line, but we don't include an example invocation for doing so, e.g. `git tag -a v0.0.4 -m "Release 0.0.4"` followed by `git push origin v0.0.4`. **Fixed in #2127.**

- [ ] In (vii), the instructions on updating the docs repository to use the new USWDS release are now out of date, due to https://github.com/18F/web-design-standards-docs/pull/349 and the fact that we're now pulling uswds directly from git instead of npm as of https://github.com/18F/web-design-standards-docs/pull/357. Since that process can change even more in the future, I recommend just creating a `RELEASE.md` in the docs repo, and pointing readers to it. Such information is "owned" by the docs repo anyways, and it's much more likely that it'll be kept up-to-date than if we include it in this repo. **Update:** filed #2155 in the interim.

- [x] The instructions never mention how to make sure the assets ZIP file shows up in the GitHub release page. As far as I can tell, this is done by manually dragging it over from the `dist` directory when creating the new release on the GitHub side. We should verify this with @donjo and then add it to the instructions. **Fixed in #2127.**

- [x] We should mention somewhere that CircleCI takes care of running `npm publish` when pushing to `master`.  It's not obvious, which makes it seem like we forgot to include instructions on how/when to publish to npm. **Fixed in #2127.**

- [x] We should also mention that pushes to master automatically update [components.standards.usa.gov](components.standards.usa.gov), too. **Fixed in #2127.**
