### ISSUE TITLE
Determine process for creating and evaluating component candidates 

### ISSUE THREAD

**Issue by thisisdano** [18F/web-design-standards#2204]
When should we create a new component in the System? What justifies a new component and how do we evaluate when a component is ready to add? Let's get some clarity and direction around adding new components.

Thanks to @maya we have something from Nathan Curtis:
https://medium.com/eightshapes-llc/i-made-this-does-it-go-in-the-system-3b67b9894531

And thanks to @line47 we have something from Brad Frost:
![pattern-addition-flowchart.png](https://images.zenhubusercontent.com/5748bc2dbf93871ccd9bbeaa/22ac8702-09eb-4e00-a18b-120f42597269)

### todo
- [ ] meet to discuss new component workflow
- [ ] draft a proposal for this new component process
- [ ] get feedback from relevant peers/community
- [ ] add this documentation to the site and the repo

_Possibly an epic_

**Comment by maya** [comment]
Started a scratchpad as well to start thinking about this:  https://docs.google.com/document/d/1_dMUDbk0soPjPeqUaY1Xvl1CyYd0bACgGkMeBjlx0OE/edit#
