### ISSUE TITLE
Identify explicit needs, pain points, dreams, and opportunities for the USWDS

### ISSUE THREAD

**Issue by thisisdano** [18F/web-design-standards#2205]
Issues are important, but perhaps insufficient for determining our vision for the USWDS.

How can we see the forest in the trees and identify areas of critical focus? How do these areas align with specific user needs, contemporary best practices, and long-term resiliency?

Let's get some of our pain, our hopes, and our dreams out into the open and give em some good old fashioned clear-eyed analysis. Let's build from existing strategy and revisit the ambition, methodology, and optimism that brought us to this point.

### todo
- [ ] meet to create a collaborative mural
- [ ] bring specific feedback, pain points, and opportunities
- [ ] bring examples from existing design systems
- [ ] bring existing strategy work and relevant assets
- [ ] create cards, then group and analyze
- [ ] identify known blind spots
- [ ] identify areas for research
- [ ] create a strategic proposal and collect feedback from peers/community 
- [ ] publish final strategic roadmap on the site

**Comment by thisisdano** [comment]
### Mural
![29d32c04-97c3-44d6-aa51-339a910cfe20](https://user-images.githubusercontent.com/11464021/32867051-adc61878-ca1f-11e7-9826-af87c546f429.png)

### Voting results
![roadmap voting results](https://user-images.githubusercontent.com/11464021/32867061-bf818714-ca1f-11e7-8b10-73a592e97b2d.png)

**Comment by thisisdano** [comment]
Publish roadmap to site
