### ISSUE TITLE
Deprecating `usa-input-required` has important backward-compatibility concerns 

### ISSUE THREAD

**Issue by thisisdano** [18F/web-design-standards#2238]
In [version 1.4.0](https://github.com/18F/web-design-standards/releases/tag/v1.4.0) we indicated that we would deprecate `usa-input-required` unless a compelling argument existed to keep it.

> A new `usa-input-optional` class has been added in favor of `usa-input-required` (#2116). The latter is now deprecated and will be removed in a future release of the Standards, due to evidence that labeling optional fields over required ones is a best practice. If you feel strongly about this issue, however, please contact the Standards team, as we may un-deprecate `usa-input-required` if a compelling argument exists.

#### references
http://uxmovement.com/forms/why-users-fill-out-less-if-you-mark-required-fields/
https://www.nngroup.com/articles/web-form-design/
http://govuk-elements.herokuapp.com/form-elements#form-optional-fields

While it makes very good sense to promote best practices, deprecating critical component variants is a challenge. The Standards should be a clear guide for best practices and we should not actively enable non–best practices unless we have little choice. This may be one of those cases where there's not only a large potential gap between the best practice and user expectations, but also a case where our our earlier support for `usa-input-required` resulted in a support expectation for a critical element (forms) that we may have the responsibility to maintain.

### todo
- [x] evaluate whether it makes sense to continue to deprecate `usa-input-required`
- [ ] if not, determine how to support our best-practice guidance alongside legacy needs
- [ ] implement this solution and communicate it to our users in release notes and documentation

**Comment by maya** [comment]
These are still part of the codebase here: https://github.com/18F/web-design-standards/blob/develop/src/stylesheets/elements/_inputs.scss#L89-#L92.

We discussed that we did not plan to deprecate these in terms of removing them from the codebase, we will just not be advocating them as a "best practice." Teams may decide to use the required field if it makes sense for their use cases.

**Comment by amilie** [comment]
@maya That sounds great. Does that mean that the following item in the v1.4.0 release notes is no longer accurate?

> A new `usa-input-optional` class has been added in favor of `usa-input-required` (#2116). The latter is now deprecated and will be removed in a future release of the Standards

**Comment by maya** [comment]
@amilie Correct! I don't believe we have plans to remove it, so that is no longer accurate.

**Comment by toolness** [comment]
Thanks @maya, I've just updated the [release notes for 1.4.0](https://github.com/18F/web-design-standards/releases/tag/v1.4.0) to reflect this:

> <img width="742" alt="screen shot 2017-11-20 at 8 31 23 am" src="https://user-images.githubusercontent.com/124687/33020728-4e89c8e4-cdcd-11e7-8360-f6c77c4c170c.png">

I also just filed https://github.com/18F/web-design-standards-docs/issues/455 to ensure that `usa-input-required` becomes documented (lest this become a secret feature that only long-time users of the standards know about).
