### ISSUE TITLE
Tracking performance of web design standards

### ISSUE THREAD

**Issue by msecret** [18F/web-design-standards#815]
As the standards grow, I think it's important to measure the performance impacts of using the library to ensure as change come in performance doesn't degrade down to unacceptable levels.

I think the best way to do this would be to add performance tracking to example template pages we've discussed creating: https://github.com/18F/web-design-standards/issues/759. In terms of metrics, I'd suggest something generic like speed index as the main metric. I'd image this would be part of the CI process OR something similar to speedcurve.com, where we'd just track over time.

I don't think we need any hard and fast rules on what would be acceptable performance, because people could leverage additional techniques (critical CSS, etc) to improve performance on their sites. I think it's just good to have an eye on performance as development continues

**Comment by mollieru** [comment]
Cool, good idea @msecret -- we'll consider this in our future roadmap.

**Comment by shawnbot** [comment]
I'm upgrading the priority for this one because we need to be able to measure performance before we start trying to improve it.

**Comment by yowill** [comment]
@lauraponce Check this out!

**Comment by shawnbot** [comment]
Okay, so after a bit of research, I think there are a bunch of tasks to stub out in separate issues for this one. As I write this, I'm thinking that we probably won't get all of this done in a single sprint.

- [ ] Decide which metrics to measure
- [ ] Decide which tool(s) to use
- [ ] Get this repo to generate testable HTML files, and possibly to publish them somewhere public (Federalist) that they can be tested by services such as [Google PageSpeed Insights]
- [ ] Get reporting working on our CI service with the chosen tool(s)
- [ ] Figure out how to track variance (e.g. between scores on a given branch and `master`, which is how our code coverage tracking works), where reports "live" that they can be compared (CI build artifacts?), etc.
- [ ] Decide if, and under which conditions, a variance fails a CI build (e.g. if the [Google PageSpeed Insights] score goes down by 5 points or more, or if the [YSlow] grade drops)
- [ ] Run through the process a couple of times to test and validate it

Before I go and start filing issues, does anyone have any thoughts? Are these tasks too granular, or not granular enough? @msecret @lauraponce @juliaelman @yowill 

Also, I have a lot more written down about tools, but I didn't want to dump it all here.

[Google PageSpeed Insights]: https://developers.google.com/speed/pagespeed/insights/
[YSlow]: http://yslow.org/

**Comment by shawnbot** [comment]
Okay, and with #1791 all of the sub-tasks from the above comment have been broken out. We're going to close this issue and move forward with the more granular ones. ✌️
